version: '2.1'
orbs:
  kubernetes: circleci/kubernetes@1.3

jobs:
  test-cluster:
    docker:
      - image: 'cimg/python:3.10'
    steps:
      - checkout
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: geohospital
      - run:
          command: |
            kubectl get svc
          name: Test cluster

workflows:
  deployment:
    jobs:
      - test-cluster