version: '2.1'
orbs:
  kubernetes: circleci/kubernetes@1.3

jobs:
  test-cluster:
    docker:
      - image: 'weaveworks/eksctl'
    steps:
      - run:
          command: |
            eksctl create cluster
          name: Test cluster

workflows:
  deployment:
    jobs:
      - test-cluster