version: '2.1'
orbs:
  kubernetes: circleci/kubernetes@1.3
  aws-eks: circleci/aws-eks@2.1.1
  rnikkei-yq: nikkei/rnikkei-yq@0.0.3

jobs:

  convert_files:
    docker:
      - image: 'cimg/python:3.10'
    steps:
      - checkout
      - run:
          name: "add yd"
          command: |
            wget https://github.com/mikefarah/yq/releases/download/4.19.1/yq_linux_amd64 -O /usr/bin/yq &&\
            sudo chmod +x /usr/bin/yq
      # - rnikkei-yq/install:
      #     version: "4.19.1"
      - run:
          name: "test yd"
          command: |
            yq -i '.jobs.test-cluster.docker = "cool"' config.bk2.yml

  test-cluster:
    docker:
      - image: 'cimg/python:3.10'
    steps:
      - checkout
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: geohospital
      - run:
          command: |
            kubectl get svc
          name: Test cluster

workflows:
  deployment:
    jobs:
      - test-cluster
      - convert_files